{{- $ns := .Values.namespace | default .Release.Namespace -}}
{{- range $name, $svc := .Values.services }}
{{- if $svc.externalSecret }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ $svc.externalSecret.secretStoreName }}
  namespace: {{ $ns }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: {{ $svc.sa.name }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $name }}-es
  namespace: {{ $ns }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $svc.externalSecret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ $name }}-secrets
    creationPolicy: Owner
  data:
  {{- range $svc.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
        {{- if .property }}
        property: {{ .property }}
        {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}

