{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msa-ingress
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
{{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
{{- range $name, $svc := .Values.services }}
      - path: /{{ $name }}
        pathType: Prefix
        backend:
          service:
            name: {{ $name }}
            port:
              number: {{ $svc.port }}
{{- end }}
{{- end }}

