{{- $ns := .Values.namespace | default .Release.Namespace -}}
{{- range $name, $svc := .Values.services }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ $name }}
  namespace: {{ $ns }}
spec:
  replicas: 2
  selector:
    matchLabels: { app: {{ $name }} }
  template:
    metadata:
      labels: { app: {{ $name }} }
    spec:
      serviceAccountName: {{ $svc.sa.name }}
      containers:
        - name: {{ $name }}
          image: {{ $svc.image }}
          imagePullPolicy: {{ $svc.imagePullPolicy | default $.Values.global.imagePullPolicy }}
          ports: [{ containerPort: {{ $svc.port }} }]
          envFrom:
            - configMapRef: { name: {{ $.Values.global.commonConfigName }} }
            {{- if $svc.configMap }}
            - configMapRef: { name: {{ $svc.configMap.name }} }
            {{- end }}
            {{- if $svc.externalSecret }}
            - secretRef:    { name: {{ $name }}-secrets }
            {{- end }}
  strategy:
    canary:
      canaryService: {{ $name }}-canary
      stableService: {{ $name }}-stable
      trafficRouting:
        alb:
          ingress: msa-ingress
          servicePort: {{ $svc.port }}
      steps:
      - setWeight: 25
      - pause: { duration: 60 }
      - setWeight: 50
      - pause: { duration: 60 }
      - setWeight: 100
---
{{- end }}
