{{- $ns := .Values.namespace | default .Release.Namespace -}}
{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $ns }}
spec:
  type: ClusterIP
  selector: { app: {{ $name }} }
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
---
{{- end }}

