apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msa-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/order-platform-gitops.git
    targetRevision: main
    path: charts/msa-apps
    helm:
      valueFiles:
        - ../../env/msa-apps/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: msa-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
